// All 25 coping skills from the Coping Skills Menu, organized by tier

export interface Skill {
  id: string;
  name: string;
  description: string;
  instructions: string;
  tier: "QUICK_STARTERS" | "MAIN_REGULATION" | "EMERGENCY_RESET" | "COMFORT_PICKS" | "DAILY_MAINTENANCE";
  duration: string;
  energyLevel: "LOW" | "MEDIUM" | "HIGH";
  icon: string;
}

export const SKILLS: Skill[] = [
  // ─── Quick Starters ─────────────────────────────────────
  {
    id: "qs-1",
    name: "Box Breathing",
    description: "Inhale 4, hold 4, exhale 4 — repeat to calm your nervous system fast.",
    instructions: "1. Inhale slowly through your nose for 4 counts\n2. Hold your breath for 4 counts\n3. Exhale slowly through your mouth for 4 counts\n4. Hold empty for 4 counts\n5. Repeat 4-6 cycles",
    tier: "QUICK_STARTERS",
    duration: "2-5 min",
    energyLevel: "LOW",
    icon: "Wind",
  },
  {
    id: "qs-2",
    name: "Name 5 Things You See",
    description: "A quick grounding exercise to anchor you in the present moment.",
    instructions: "1. Look around and name 5 things you can see\n2. Name 4 things you can physically feel\n3. Name 3 things you can hear\n4. Name 2 things you can smell\n5. Name 1 thing you can taste\nTake your time with each one.",
    tier: "QUICK_STARTERS",
    duration: "2-3 min",
    energyLevel: "LOW",
    icon: "Eye",
  },
  {
    id: "qs-3",
    name: "Shoulder Roll & Stretch",
    description: "Release physical tension with simple shoulder rolls and a quick stretch.",
    instructions: "1. Sit or stand comfortably\n2. Roll your shoulders forward 5 times\n3. Roll your shoulders backward 5 times\n4. Reach both arms overhead and stretch\n5. Drop your shoulders and take 3 deep breaths",
    tier: "QUICK_STARTERS",
    duration: "2 min",
    energyLevel: "LOW",
    icon: "Move",
  },
  {
    id: "qs-4",
    name: "Mindful Sipping",
    description: "Focus completely on the sensation of slowly drinking water.",
    instructions: "1. Pour a glass of water\n2. Hold it and notice the temperature\n3. Take a slow sip, feeling it in your mouth\n4. Swallow mindfully, tracking the sensation\n5. Repeat 5-10 sips with full attention",
    tier: "QUICK_STARTERS",
    duration: "2-3 min",
    energyLevel: "LOW",
    icon: "Droplets",
  },
  {
    id: "qs-5",
    name: "Change Position",
    description: "Break the mental loop by physically moving your body.",
    instructions: "1. Notice your current position\n2. Stand up, walk to another room, or stretch\n3. If sitting, try standing; if inside, step outside\n4. Take 5 deep breaths in the new position\n5. Notice how your body feels different",
    tier: "QUICK_STARTERS",
    duration: "1-2 min",
    energyLevel: "LOW",
    icon: "ArrowUpRight",
  },
  // ─── Main Regulation ───────────────────────────────────
  {
    id: "mr-1",
    name: "Thought Reframing",
    description: "Challenge your thoughts by asking 'What else could be true?'",
    instructions: "1. Notice the thought causing distress\n2. Write it down: 'I feel X because I think Y'\n3. Ask: What evidence supports this thought?\n4. Ask: What evidence contradicts it?\n5. Ask: What else could be true?\n6. Write a balanced alternative thought",
    tier: "MAIN_REGULATION",
    duration: "10-15 min",
    energyLevel: "MEDIUM",
    icon: "Brain",
  },
  {
    id: "mr-2",
    name: "Journaling Emotional Dump",
    description: "Write freely for 10 minutes to process and release pent-up emotions.",
    instructions: "1. Set a timer for 10 minutes\n2. Write whatever comes to mind — no filtering\n3. Don't worry about grammar or logic\n4. Let emotions flow onto the page\n5. When the timer ends, read what you wrote\n6. Circle any patterns or recurring themes",
    tier: "MAIN_REGULATION",
    duration: "10-15 min",
    energyLevel: "MEDIUM",
    icon: "PenLine",
  },
  {
    id: "mr-3",
    name: "Guided Body Scan",
    description: "Systematically bring awareness to each part of your body to release tension.",
    instructions: "1. Lie down or sit comfortably\n2. Close your eyes and take 3 deep breaths\n3. Start at your toes — notice any tension\n4. Slowly move up: feet, calves, knees, thighs\n5. Continue through hips, stomach, chest, arms\n6. Finish with neck, jaw, and forehead\n7. Breathe into any tight spots for 5 seconds each",
    tier: "MAIN_REGULATION",
    duration: "10-15 min",
    energyLevel: "MEDIUM",
    icon: "Scan",
  },
  {
    id: "mr-4",
    name: "Progressive Muscle Relaxation",
    description: "Tense and release muscle groups to deeply relax your body.",
    instructions: "1. Start with your toes — tense for 5 seconds\n2. Release suddenly and notice the relaxation\n3. Move to calves: tense, hold, release\n4. Continue upward: thighs, stomach, chest\n5. Arms, hands, shoulders\n6. Face: squeeze eyes, clench jaw, release\n7. Finish with full-body relaxation",
    tier: "MAIN_REGULATION",
    duration: "15-20 min",
    energyLevel: "MEDIUM",
    icon: "Activity",
  },
  {
    id: "mr-5",
    name: "Mindful Walking",
    description: "Walk slowly with full attention on each step and sensation.",
    instructions: "1. Find a quiet space, indoors or outdoors\n2. Walk at half your normal speed\n3. Notice the heel touching the ground\n4. Feel the weight shift to the ball of your foot\n5. Notice the lift of the other foot\n6. If your mind wanders, gently return to the steps\n7. Continue for 5-10 minutes",
    tier: "MAIN_REGULATION",
    duration: "10-15 min",
    energyLevel: "MEDIUM",
    icon: "Footprints",
  },
  // ─── Emergency Reset ───────────────────────────────────
  {
    id: "er-1",
    name: "Cold Water Splash",
    description: "Activate the mammalian dive reflex to rapidly calm your nervous system.",
    instructions: "1. Go to a sink or bathroom\n2. Splash cold water on your face\n3. Or hold an ice cube in your hand\n4. Focus on the cold sensation\n5. Notice your heart rate beginning to slow\n6. Repeat if needed after 30 seconds",
    tier: "EMERGENCY_RESET",
    duration: "1-2 min",
    energyLevel: "LOW",
    icon: "Thermometer",
  },
  {
    id: "er-2",
    name: "5-4-3-2-1 Sensory Grounding",
    description: "Engage all five senses to pull yourself out of a spiral.",
    instructions: "1. Say aloud 5 things you can SEE\n2. Say aloud 4 things you can TOUCH\n3. Say aloud 3 things you can HEAR\n4. Say aloud 2 things you can SMELL\n5. Say aloud 1 thing you can TASTE\nMove slowly through each step. Speak each item out loud.",
    tier: "EMERGENCY_RESET",
    duration: "3-5 min",
    energyLevel: "LOW",
    icon: "Hand",
  },
  {
    id: "er-3",
    name: "Extended Exhale Breathing",
    description: "Longer exhales activate your parasympathetic nervous system.",
    instructions: "1. Inhale through your nose for 4 counts\n2. Exhale through your mouth for 8 counts\n3. Focus on making the exhale slow and steady\n4. If 8 is too much, try exhale for 6\n5. Repeat 6-10 times\n6. Let your breathing return to natural rhythm",
    tier: "EMERGENCY_RESET",
    duration: "2-3 min",
    energyLevel: "LOW",
    icon: "Waves",
  },
  {
    id: "er-4",
    name: "Step Away",
    description: "Physically remove yourself from the triggering environment immediately.",
    instructions: "1. Notice: I need to leave this situation\n2. Say aloud: 'I'm stepping away for a moment'\n3. Walk to a different room or go outside\n4. If with others: 'I need a few minutes'\n5. Once in a new space, take 5 deep breaths\n6. Use another grounding tool if needed",
    tier: "EMERGENCY_RESET",
    duration: "1-2 min",
    energyLevel: "LOW",
    icon: "DoorOpen",
  },
  {
    id: "er-5",
    name: "Safe Phrase Repeat",
    description: "Repeat a grounding phrase: 'I am safe right now.'",
    instructions: "1. Choose your safe phrase: 'I am safe right now'\n2. Say it aloud or in your mind\n3. Repeat slowly 10 times\n4. With each repetition, slow down\n5. Notice your breathing calming\n6. Feel your feet on the ground\n7. Repeat as many times as needed",
    tier: "EMERGENCY_RESET",
    duration: "2-3 min",
    energyLevel: "LOW",
    icon: "Shield",
  },
  // ─── Comfort Picks ─────────────────────────────────────
  {
    id: "cp-1",
    name: "Wrap in a Blanket",
    description: "Deep pressure from a cozy blanket signals safety to your body.",
    instructions: "1. Get your favorite blanket or throw\n2. Wrap yourself snugly, like a burrito\n3. Lie down or sit comfortably\n4. Notice the warmth and texture\n5. Stay wrapped for at least 5 minutes\n6. Let yourself simply be held",
    tier: "COMFORT_PICKS",
    duration: "5-10 min",
    energyLevel: "LOW",
    icon: "Bed",
  },
  {
    id: "cp-2",
    name: "Calming Music",
    description: "Let soothing sounds wash over you and reset your emotional state.",
    instructions: "1. Put on headphones or play softly\n2. Choose calming music, nature sounds, or white noise\n3. Close your eyes if comfortable\n4. Focus on one instrument or sound layer\n5. Let the music carry your thoughts\n6. Stay for at least one full song",
    tier: "COMFORT_PICKS",
    duration: "5-15 min",
    energyLevel: "LOW",
    icon: "Music",
  },
  {
    id: "cp-3",
    name: "Pleasant Scent",
    description: "Aromatherapy engages your limbic system to shift your mood gently.",
    instructions: "1. Light a candle, use essential oil, or open a scent\n2. Lavender, vanilla, and cedar are calming choices\n3. Close your eyes and breathe in slowly\n4. Notice where you feel the scent in your body\n5. Take 5-10 slow breaths with the scent\n6. Let the aroma create a cozy atmosphere",
    tier: "COMFORT_PICKS",
    duration: "5 min",
    energyLevel: "LOW",
    icon: "Flame",
  },
  {
    id: "cp-4",
    name: "Comfort Show",
    description: "Watch something familiar and safe — no new stressors, just warmth.",
    instructions: "1. Pick a show or movie you've seen before\n2. The familiarity is the point — no surprises\n3. Get cozy with a blanket or snack\n4. Let your mind rest on predictable content\n5. Watch for 20-30 minutes\n6. Notice tension leaving your body",
    tier: "COMFORT_PICKS",
    duration: "20-30 min",
    energyLevel: "LOW",
    icon: "Tv",
  },
  {
    id: "cp-5",
    name: "Hand on Heart",
    description: "Self-compassion touch activates the care-and-soothing system.",
    instructions: "1. Place your right hand over your heart\n2. Feel the warmth of your palm\n3. Feel your heartbeat beneath your hand\n4. Say to yourself: 'This is a moment of suffering'\n5. Then: 'Suffering is part of being human'\n6. Then: 'May I be kind to myself right now'\n7. Stay for 1-2 minutes, breathing gently",
    tier: "COMFORT_PICKS",
    duration: "2-5 min",
    energyLevel: "LOW",
    icon: "Heart",
  },
  // ─── Daily Maintenance ─────────────────────────────────
  {
    id: "dm-1",
    name: "Sleep Routine",
    description: "Consistent sleep is the foundation of emotional resilience.",
    instructions: "1. Set a consistent bedtime (within 30 min window)\n2. Begin winding down 1 hour before bed\n3. Dim lights, reduce screen time\n4. Do a relaxing activity: reading, stretching\n5. Keep your room cool, dark, and quiet\n6. Aim for 7-9 hours consistently",
    tier: "DAILY_MAINTENANCE",
    duration: "Ongoing",
    energyLevel: "MEDIUM",
    icon: "Moon",
  },
  {
    id: "dm-2",
    name: "Morning Sunlight",
    description: "Morning light regulates your circadian rhythm and boosts mood.",
    instructions: "1. Get outside within 30 minutes of waking\n2. Aim for 10-20 minutes of direct sunlight\n3. No sunglasses — let light reach your eyes\n4. Even cloudy days provide enough light\n5. Combine with a short walk if possible\n6. Notice how your energy shifts afterward",
    tier: "DAILY_MAINTENANCE",
    duration: "10-20 min",
    energyLevel: "MEDIUM",
    icon: "Sun",
  },
  {
    id: "dm-3",
    name: "Gratitude Journaling",
    description: "Noticing good things rewires your brain toward positivity over time.",
    instructions: "1. Each morning or evening, write 3 things\n2. Be specific: not 'family' but 'Mom's call today'\n3. Include small things: a good coffee, sunshine\n4. Write why each one mattered to you\n5. Do this consistently for best results\n6. Review your entries weekly for patterns",
    tier: "DAILY_MAINTENANCE",
    duration: "5 min",
    energyLevel: "LOW",
    icon: "NotebookPen",
  },
  {
    id: "dm-4",
    name: "Digital Boundaries",
    description: "Manage screen time and social media to protect your mental energy.",
    instructions: "1. Set screen-free times (meals, 1 hour before bed)\n2. Use Do Not Disturb during focus or rest\n3. Unfollow accounts that drain you\n4. Set a daily social media time limit\n5. Charge your phone outside the bedroom\n6. Notice how you feel after less screen time",
    tier: "DAILY_MAINTENANCE",
    duration: "Ongoing",
    energyLevel: "MEDIUM",
    icon: "SmartphoneOff",
  },
  {
    id: "dm-5",
    name: "Daily Movement",
    description: "Regular exercise is one of the most powerful mood regulators.",
    instructions: "1. Pick a movement you enjoy — walking, yoga, dancing\n2. Aim for 20-30 minutes daily\n3. Even 10 minutes makes a difference\n4. Do it at the same time each day to build habit\n5. Notice your mood before and after\n6. Combine with sunlight for extra benefit",
    tier: "DAILY_MAINTENANCE",
    duration: "20-30 min",
    energyLevel: "MEDIUM",
    icon: "Running",
  },
];

// Mood → Tier mapping (based on the Coping Skills Menu energy-level guidance)
export const MOOD_TIER_MAP: Record<string, string[]> = {
  overwhelmed: ["EMERGENCY_RESET", "QUICK_STARTERS"],
  scattered: ["QUICK_STARTERS", "MAIN_REGULATION"],
  exhausted: ["COMFORT_PICKS", "DAILY_MAINTENANCE"],
  anxious: ["EMERGENCY_RESET", "QUICK_STARTERS"],
  fine: ["QUICK_STARTERS", "DAILY_MAINTENANCE"],
  low: ["COMFORT_PICKS", "DAILY_MAINTENANCE"],
};
